[2025-06-09T15:14:25.793+0000] {processor.py:161} INFO - Started process (PID=45) to work on /opt/airflow/dags/extract.py
[2025-06-09T15:14:25.802+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2025-06-09T15:14:25.807+0000] {logging_mixin.py:188} INFO - [2025-06-09T15:14:25.807+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2025-06-09T15:14:25.824+0000] {logging_mixin.py:188} INFO - [2025-06-09T15:14:25.822+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 5, in <module>
    from explore_data import filter_sensors_location, filter_values_by_sensor
ModuleNotFoundError: No module named 'explore_data'
[2025-06-09T15:14:25.825+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2025-06-09T15:14:25.849+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/extract.py took 0.060 seconds
[2025-06-09T15:14:56.544+0000] {processor.py:161} INFO - Started process (PID=101) to work on /opt/airflow/dags/extract.py
[2025-06-09T15:14:56.548+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2025-06-09T15:14:56.551+0000] {logging_mixin.py:188} INFO - [2025-06-09T15:14:56.551+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2025-06-09T15:14:56.574+0000] {logging_mixin.py:188} INFO - [2025-06-09T15:14:56.572+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 5, in <module>
    from explore_data import filter_sensors_location, filter_values_by_sensor
ModuleNotFoundError: No module named 'explore_data'
[2025-06-09T15:14:56.574+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2025-06-09T15:14:56.611+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/extract.py took 0.077 seconds
[2025-06-09T15:15:26.695+0000] {processor.py:161} INFO - Started process (PID=157) to work on /opt/airflow/dags/extract.py
[2025-06-09T15:15:26.700+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2025-06-09T15:15:26.704+0000] {logging_mixin.py:188} INFO - [2025-06-09T15:15:26.703+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2025-06-09T15:15:26.710+0000] {logging_mixin.py:188} INFO - [2025-06-09T15:15:26.709+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 5, in <module>
    from explore_data import filter_sensors_location, filter_values_by_sensor
ModuleNotFoundError: No module named 'explore_data'
[2025-06-09T15:15:26.710+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2025-06-09T15:15:26.726+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/extract.py took 0.039 seconds
[2025-06-09T15:15:57.643+0000] {processor.py:161} INFO - Started process (PID=213) to work on /opt/airflow/dags/extract.py
[2025-06-09T15:15:57.650+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2025-06-09T15:15:57.653+0000] {logging_mixin.py:188} INFO - [2025-06-09T15:15:57.652+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2025-06-09T15:15:57.676+0000] {logging_mixin.py:188} INFO - [2025-06-09T15:15:57.670+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 5, in <module>
    from explore_data import filter_sensors_location, filter_values_by_sensor
ModuleNotFoundError: No module named 'explore_data'
[2025-06-09T15:15:57.809+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2025-06-09T15:15:57.833+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/extract.py took 0.198 seconds
[2025-06-09T15:16:27.985+0000] {processor.py:161} INFO - Started process (PID=268) to work on /opt/airflow/dags/extract.py
[2025-06-09T15:16:27.986+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2025-06-09T15:16:27.989+0000] {logging_mixin.py:188} INFO - [2025-06-09T15:16:27.989+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2025-06-09T15:16:28.002+0000] {logging_mixin.py:188} INFO - [2025-06-09T15:16:28.001+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 5, in <module>
    from explore_data import filter_sensors_location, filter_values_by_sensor
ModuleNotFoundError: No module named 'explore_data'
[2025-06-09T15:16:28.002+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2025-06-09T15:16:28.034+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/extract.py took 0.058 seconds
[2025-06-09T15:16:58.271+0000] {processor.py:161} INFO - Started process (PID=324) to work on /opt/airflow/dags/extract.py
[2025-06-09T15:16:58.277+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2025-06-09T15:16:58.296+0000] {logging_mixin.py:188} INFO - [2025-06-09T15:16:58.295+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2025-06-09T15:16:58.320+0000] {logging_mixin.py:188} INFO - [2025-06-09T15:16:58.318+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 5, in <module>
    from explore_data import filter_sensors_location, filter_values_by_sensor
ModuleNotFoundError: No module named 'explore_data'
[2025-06-09T15:16:58.320+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2025-06-09T15:16:58.395+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/extract.py took 0.158 seconds
[2025-06-09T15:17:28.767+0000] {processor.py:161} INFO - Started process (PID=380) to work on /opt/airflow/dags/extract.py
[2025-06-09T15:17:28.771+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2025-06-09T15:17:28.782+0000] {logging_mixin.py:188} INFO - [2025-06-09T15:17:28.781+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2025-06-09T15:17:28.794+0000] {logging_mixin.py:188} INFO - [2025-06-09T15:17:28.792+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 5, in <module>
    from explore_data import filter_sensors_location, filter_values_by_sensor
ModuleNotFoundError: No module named 'explore_data'
[2025-06-09T15:17:28.794+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2025-06-09T15:17:28.839+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/extract.py took 0.094 seconds
[2025-06-09T15:17:58.990+0000] {processor.py:161} INFO - Started process (PID=436) to work on /opt/airflow/dags/extract.py
[2025-06-09T15:17:58.993+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2025-06-09T15:17:58.995+0000] {logging_mixin.py:188} INFO - [2025-06-09T15:17:58.995+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2025-06-09T15:17:59.014+0000] {logging_mixin.py:188} INFO - [2025-06-09T15:17:59.013+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 5, in <module>
    from explore_data import filter_sensors_location, filter_values_by_sensor
ModuleNotFoundError: No module named 'explore_data'
[2025-06-09T15:17:59.014+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2025-06-09T15:17:59.041+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/extract.py took 0.056 seconds
[2025-06-09T15:18:29.906+0000] {processor.py:161} INFO - Started process (PID=498) to work on /opt/airflow/dags/extract.py
[2025-06-09T15:18:29.909+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2025-06-09T15:18:29.915+0000] {logging_mixin.py:188} INFO - [2025-06-09T15:18:29.914+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2025-06-09T15:18:29.931+0000] {logging_mixin.py:188} INFO - [2025-06-09T15:18:29.928+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 5, in <module>
    from explore_data import filter_sensors_location, filter_values_by_sensor
ModuleNotFoundError: No module named 'explore_data'
[2025-06-09T15:18:29.931+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2025-06-09T15:18:29.961+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/extract.py took 0.065 seconds
[2025-06-09T15:19:00.647+0000] {processor.py:161} INFO - Started process (PID=554) to work on /opt/airflow/dags/extract.py
[2025-06-09T15:19:00.648+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2025-06-09T15:19:00.653+0000] {logging_mixin.py:188} INFO - [2025-06-09T15:19:00.653+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2025-06-09T15:19:00.666+0000] {logging_mixin.py:188} INFO - [2025-06-09T15:19:00.665+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 5, in <module>
    from explore_data import filter_sensors_location, filter_values_by_sensor
ModuleNotFoundError: No module named 'explore_data'
[2025-06-09T15:19:00.666+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2025-06-09T15:19:00.692+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/extract.py took 0.051 seconds
[2025-06-09T15:19:31.158+0000] {processor.py:161} INFO - Started process (PID=610) to work on /opt/airflow/dags/extract.py
[2025-06-09T15:19:31.161+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2025-06-09T15:19:31.163+0000] {logging_mixin.py:188} INFO - [2025-06-09T15:19:31.163+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2025-06-09T15:19:31.173+0000] {logging_mixin.py:188} INFO - [2025-06-09T15:19:31.173+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 5, in <module>
    from explore_data import filter_sensors_location, filter_values_by_sensor
ModuleNotFoundError: No module named 'explore_data'
[2025-06-09T15:19:31.175+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2025-06-09T15:19:31.188+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/extract.py took 0.039 seconds
[2025-06-09T15:20:01.784+0000] {processor.py:161} INFO - Started process (PID=666) to work on /opt/airflow/dags/extract.py
[2025-06-09T15:20:01.785+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2025-06-09T15:20:01.790+0000] {logging_mixin.py:188} INFO - [2025-06-09T15:20:01.790+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2025-06-09T15:20:01.806+0000] {logging_mixin.py:188} INFO - [2025-06-09T15:20:01.802+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 5, in <module>
    from explore_data import filter_sensors_location, filter_values_by_sensor
ModuleNotFoundError: No module named 'explore_data'
[2025-06-09T15:20:01.806+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2025-06-09T15:20:01.821+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/extract.py took 0.041 seconds
[2025-06-09T15:20:32.010+0000] {processor.py:161} INFO - Started process (PID=722) to work on /opt/airflow/dags/extract.py
[2025-06-09T15:20:32.013+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2025-06-09T15:20:32.020+0000] {logging_mixin.py:188} INFO - [2025-06-09T15:20:32.019+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2025-06-09T15:20:32.030+0000] {logging_mixin.py:188} INFO - [2025-06-09T15:20:32.029+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 5, in <module>
    from explore_data import filter_sensors_location, filter_values_by_sensor
ModuleNotFoundError: No module named 'explore_data'
[2025-06-09T15:20:32.031+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2025-06-09T15:20:32.050+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/extract.py took 0.044 seconds
[2025-06-09T15:21:02.904+0000] {processor.py:161} INFO - Started process (PID=778) to work on /opt/airflow/dags/extract.py
[2025-06-09T15:21:02.910+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2025-06-09T15:21:02.912+0000] {logging_mixin.py:188} INFO - [2025-06-09T15:21:02.911+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2025-06-09T15:21:02.920+0000] {logging_mixin.py:188} INFO - [2025-06-09T15:21:02.919+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 5, in <module>
    from explore_data import filter_sensors_location, filter_values_by_sensor
ModuleNotFoundError: No module named 'explore_data'
[2025-06-09T15:21:02.920+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2025-06-09T15:21:02.934+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/extract.py took 0.034 seconds
[2025-06-09T15:21:33.098+0000] {processor.py:161} INFO - Started process (PID=834) to work on /opt/airflow/dags/extract.py
[2025-06-09T15:21:33.100+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2025-06-09T15:21:33.104+0000] {logging_mixin.py:188} INFO - [2025-06-09T15:21:33.103+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2025-06-09T15:21:33.114+0000] {logging_mixin.py:188} INFO - [2025-06-09T15:21:33.112+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 5, in <module>
    from explore_data import filter_sensors_location, filter_values_by_sensor
ModuleNotFoundError: No module named 'explore_data'
[2025-06-09T15:21:33.114+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2025-06-09T15:21:33.139+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/extract.py took 0.048 seconds
[2025-06-09T15:22:03.228+0000] {processor.py:161} INFO - Started process (PID=890) to work on /opt/airflow/dags/extract.py
[2025-06-09T15:22:03.229+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2025-06-09T15:22:03.235+0000] {logging_mixin.py:188} INFO - [2025-06-09T15:22:03.234+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2025-06-09T15:22:03.254+0000] {logging_mixin.py:188} INFO - [2025-06-09T15:22:03.253+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 5, in <module>
    from explore_data import filter_sensors_location, filter_values_by_sensor
ModuleNotFoundError: No module named 'explore_data'
[2025-06-09T15:22:03.254+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2025-06-09T15:22:03.279+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/extract.py took 0.057 seconds
[2025-06-09T15:22:33.443+0000] {processor.py:161} INFO - Started process (PID=946) to work on /opt/airflow/dags/extract.py
[2025-06-09T15:22:33.445+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2025-06-09T15:22:33.449+0000] {logging_mixin.py:188} INFO - [2025-06-09T15:22:33.447+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2025-06-09T15:22:33.459+0000] {logging_mixin.py:188} INFO - [2025-06-09T15:22:33.458+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 5, in <module>
    from explore_data import filter_sensors_location, filter_values_by_sensor
ModuleNotFoundError: No module named 'explore_data'
[2025-06-09T15:22:33.459+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2025-06-09T15:22:33.477+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/extract.py took 0.044 seconds
